### ISSUE TITLE
Inconsistent UI when too many dates are selected in venue selection screen.

### ISSUE THREAD

**Issue by chandrakiran343** [coding-Studio-vbit/ARMA#117]
![image](https://user-images.githubusercontent.com/80049363/169657338-580190e2-382d-422e-b7fc-2feb2a27ccbd.png)
![image](https://user-images.githubusercontent.com/80049363/169657360-a3c46de8-13f1-4368-8c88-b1d7743bcbec.png)

**Comment by bsaikiran618** [comment]
@yasaswiraj PLease fix this in venue update and create event both
