### ISSUE TITLE
Event venue card when clicked reloads page after event completed.

### ISSUE THREAD

**Issue by chandrakiran343** [coding-Studio-vbit/ARMA#130]
![image](https://user-images.githubusercontent.com/80049363/170875749-81523559-32e5-439f-a098-4a57773eb0e2.png)

is it not supposed to route anywhere? if yes, remove the click event for it.

**Comment by bsaikiran618** [comment]
This isnt happening for all the events on the dashboard, that's strange

**Comment by chandrakiran343** [comment]
it is happening after completing the event, sometimes when it is in progress also
